package com.leonside.dataroad.core.builder;

import com.leonside.dataroad.common.utils.Asserts;

import java.io.Serializable;
import java.util.concurrent.TimeUnit;

public final class Time implements Serializable {

    private static final long serialVersionUID = -350254188460915999L;

    /**
     * The time unit for this policy's time interval.
     */
    private final TimeUnit unit;

    /**
     * The size of the windows generated by this policy.
     */
    private final long size;

    /**
     * Instantiation only via factory method.
     */
    private Time(long size, TimeUnit unit) {
        Asserts.notNull(unit, "time unit may not be null");
        this.unit = unit;
        this.size = size;
    }

    public TimeUnit getUnit() {
        return unit;
    }

    public long getSize() {
        return size;
    }

    public static Time of(long size, TimeUnit unit) {
        return new Time(size, unit);
    }
}